### ISSUE TITLE
Player doesn't walk towards the crosshair

### ISSUE THREAD

**Issue by AluminumHaste** [yquake2/ref_vk#12]
For some reason, in my game the player doesn't walk towards the crosshair (center of screen) but dog tracks off to the side.
This might not be limited to this port, and this could be a Windows 11 bug.

https://i.imgur.com/HtWhW8Z.png

But when I walk I go to the left like there's an invisible wall.
Sometimes, if I move the mouse a bit it fixes it, but this really screws up the game.

Running the game at 500 fps, but also does it at lower FPS values.
Windows 11 Dev 22509.1011
AMD 5700XT - 22.1.2 driver (Latest)

**Comment by AluminumHaste** [comment]
This is also present in the original 3.20 game that's on Steam. So not this port, just something fucked up with Quake 2?

**Comment by kondrak** [comment]
Rather a by-design choice. The crosshair was only meant to point where bullets/missiles/laser beams would land, not necessarily point the direction of player movement.

**Comment by AluminumHaste** [comment]
But the crosshair is dead center, pressing forward on the keyboard should cause the player to move _forward_ not to the right.

**Comment by AluminumHaste** [comment]
Ok, forget about the crosshair, remove it.
The bug is that when the player presses the forward key, he doesn't move forward, but forward and to the right.

**Comment by DanielGibson** [comment]
what resolution are you using?

**Comment by Yamagi** [comment]
> By pressing NOTHING but forwards then backwards, the player slowly moves across the room.

That's the '0 has gravity' bug, the player is pulled towards the 0 coordinate. It happens in all three dimensions, against the X, Y and Z axis. It's caused by converting between float <-> int <-> short throughout the game and cannot be fixed. As an example: The player is at float 42.23 on the x-axis -> convert it to int -> the player "moved" to 42.

**Comment by AluminumHaste** [comment]
Oh dear god, who in the F did that at Id?

**Comment by Yamagi** [comment]
It was likely introduced as a side effect of some kind of performance optimization sometime between Quake and Quake II. Quake II uses a lot more floating point math than Quake I... Quake II is some kind of unwanted child, a Quake I which was hacked up a little bit to provide a slightly enhanced engine for a new game, while the much more advanced Quake III iteration of the technology was still in development.

**Comment by AluminumHaste** [comment]
Well, thanks for explaining it. The crappy part is now that I've noticed it, I can't unnotice it and it's ruined the game for me.
I used to think I was having issues with my mouse aiming and such.
