### ISSUE TITLE
Request: New build of the vulkan renderer

### ISSUE THREAD

**Issue by lemonzest79** [yquake2/ref_vk#14]
Hiya

I see there have been plenty of commits to the vulkan renderer but no new dll build in almost a year! could one please be put out? thanks :)

**Comment by 0lvin** [comment]
Sorry, i don't have any x86/windows device available now :-( Maybe in future with cross compile or CI/CD....

**Comment by Yamagi** [comment]
I'll build a library tomorrow or something like that.

**Comment by 0lvin** [comment]
Thank you!

**Comment by Yamagi** [comment]
Here it is: https://github.com/yquake2/ref_vk/releases/tag/v1.0.2

**Comment by lemonzest79** [comment]
Thanks :D will test it out soon

**Comment by lemonzest79** [comment]
While the dll for build 1.0.1 works fine the dll for 1.0.2 says can not load as a rendering library and falls back to opengl 3.2

**Comment by 0lvin** [comment]
Could you please attach Documents\YamagiQ2\stdout.txt ?

**Comment by lemonzest79** [comment]
[fail.txt](https://github.com/yquake2/ref_vk/files/8885839/fail.txt)
[work.txt](https://github.com/yquake2/ref_vk/files/8885840/work.txt)

I know its run in wine, just wondering why the 1.0.2 dll won't even load wheres 1.0.1 does

**Comment by lemonzest79** [comment]
I used dependancy walker and it said a mingw dll was missing, libwinpthread-1.dll so I downloaded and added it and it fired right up.

[stdout.txt](https://github.com/yquake2/ref_vk/files/8885915/stdout.txt)

**Comment by lemonzest79** [comment]
Was the dll built differently this time? mingw vs msvc for example?

**Comment by Yamagi** [comment]
Crap. I'm unable to test the Windows Vulkan build, my Windows VM doesn't support Vulkan... This is likely caused by stb (the library used for image decoding) started to require pthreads in the default configuration some time ago. The solution for Quake II itself was to switch of threading. Maybe that wasn't ported to the Vulkan renderer. I'll have a look later.

**Comment by 0lvin** [comment]
Could it be related to flags changes in https://github.com/yquake2/ref_vk/commit/93caaa67e7b9adfe3d2a7066ac31117d1319c88d ?

> my Windows VM doesn't support Vulkan...

I have previously checked with [swiftShader in VM](https://github.com/yquake2/yquake2/issues/505#issuecomment-602111682). I have compiled SwiftShader by such [instructions](https://0lvin.blogspot.com/2020/03/vulkan-software-render-linux-x8664.html).

**Comment by Yamagi** [comment]
> Could it be related to flags changes in https://github.com/yquake2/ref_vk/commit/93caaa67e7b9adfe3d2a7066ac31117d1319c88d ?

https://github.com/yquake2/yquake2/commit/a05508240ffd67f1c4fdc096cc38eab26c3dca43 was missing. mingw tries to be clever. As soon as it encounters a reference to pthreads, the threading library get's linked. It doesn't matter if it was requested at command line or not.

> I have previously checked with https://github.com/yquake2/yquake2/issues/505#issuecomment-602111682. I have compiled SwiftShader by such [instructions](https://0lvin.blogspot.com/2020/03/vulkan-software-render-linux-x8664.html).

Cool! That was a very big help.


@lemonzest79: I've updated the release at https://github.com/yquake2/ref_vk/releases/tag/v1.0.2 Can you give it another try?

**Comment by lemonzest79** [comment]
I used dependency walker to make sure libwinpthread was not linked and it was not, also removed it from my Quake2 folder and placed the new ref_vk.dll into it and everything is perfectly fine now and it runs ok :)

[stdout.txt](https://github.com/yquake2/ref_vk/files/8888526/stdout.txt)

Thanks very much

**Comment by 0lvin** [comment]
Thank you!

[OpenBenchmarking](https://openbenchmarking.org/test/pts/yquake2) has support of 8.10 version with  1.0.2 Vulkan. 

And someone has already tested [Ryzen 9 5950X with RTX 3060 Ti](https://openbenchmarking.org/result/2206174-PTS-YQUAKE2866).
