### ISSUE TITLE
Linux, Vulkan: player's hand is not rendered

### ISSUE THREAD

**Issue by thesourcehim** [yquake2/ref_vk#2]
I use some hi-res models from http://www-personal.umich.edu/~jimw/q2/ and with vulkan renderer (GeForce 740M) player's hand holding blaster is not rendered. Works fine with OpenGL.
![q2_0000](https://user-images.githubusercontent.com/4952491/109304293-1a0ff380-784d-11eb-8e46-34af6b56d950.png)

**Comment by DanielGibson** [comment]
I just found out that Github (now?) allows moving issues between repos, so I moved the open Vulkan issues from the main yquake2 repo to the ref_vk repo.

**Comment by Spirrwell** [comment]
> @Spirrwell Could you please create pull request for [ref_vk](https://github.com/yquake2/ref_vk) repository?

I can do that. I was hoping to tackle other Vulkan related issues and do a pull request then. Do you want me to just open one and add to it?

**Comment by 0lvin** [comment]
> I can do that. I was hoping to tackle other Vulkan related issues and do a pull request then. 
Pull request with WIP prefix could be useful to see progress and prevent work on same issues in same time.

**Comment by Yamagi** [comment]
Fixed by merging #5.
