### ISSUE TITLE
GUI/Model texture is upscaled in vulkan

### ISSUE THREAD

**Issue by lafoxxx92** [yquake2/ref_vk#3]
build:
8.00pre

steps:
vid_renderer vk
vid_restart
vk_texturemode vk_nearest

actual:
looks like texture size is larger, it's resampled
(i'm using the arrow as a crosshair)
![image](https://user-images.githubusercontent.com/34402711/114445622-f58f9100-9bd8-11eb-95b4-bc74e0b7fa3b.png)

"high quality resize" engaged when it shouldn't
![image](https://user-images.githubusercontent.com/34402711/114445507-d690ff00-9bd8-11eb-92d1-3f629430d007.png)

expected:
looks same as when using gl1, gl3 or soft
![image](https://user-images.githubusercontent.com/34402711/114446034-70f14280-9bd9-11eb-9264-292a92c6cc03.png)

cinematic looks properly (pixelated)
![image](https://user-images.githubusercontent.com/34402711/114445712-10fa9c00-9bd9-11eb-8b2f-0b5647e78ad7.png)

device:
windows 1909
rog strix x470-f gaming
gtx1060-6gb

**Comment by Spirrwell** [comment]
Whelp, I fixed this in my fork. I kept vk_picmip support.

This is Vulkan using VK_NEAREST and vk_postprocess 0
![q2_0091_vk](https://user-images.githubusercontent.com/8671884/120417480-e3a2b280-c32c-11eb-8aec-0cd78831f3fc.jpg)

This is GL1 using GL_NEAREST
![q2_0090_gl](https://user-images.githubusercontent.com/8671884/120417493-ec938400-c32c-11eb-8729-aea09845375a.jpg)

Identical except GL1 UI is a tiny bit brighter, but not scaled.

**Comment by Yamagi** [comment]
Fixed by merging #5.
