### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY error upon launch on linux

### ISSUE THREAD

**Issue by AT14C** [yquake2/ref_vk#34]
OS: Arch Linux x86_64 
Kernel: 6.0.5-x64v2-xanmod1-1
CPU: Intel i7-10750H (12) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2060 Mobile 

Building and using the latest commit of this repo results in a segfault before even properly launching the game on my machine. However, whenever I build and use release 1.02 from June 13th it works just fine.
![Screenshot_20221207_191655](https://user-images.githubusercontent.com/120069141/206334297-f51a08b5-ecf7-4947-b486-93c0df074a2a.png)

**Comment by turol** [comment]
Are you using the integrated Intel GPU or the Nvidia one? Do you have the correct drivers installed?

**Comment by AT14C** [comment]
> Are you using the integrated Intel GPU or the Nvidia one? Do you have the correct drivers installed?
Nvidia gpu, and I am using the official driver

> Could you please try with vk_validation = 2? It should show memory regions, I suppose that code has not found required region of memory.
> 
> Update: vk_validation is renamed to r_validatuon in master branch.
I tried it (via `quake2 +r_validation 2`), but the debug output doesn't seem to be much more verbose
![image](https://user-images.githubusercontent.com/120069141/206573692-7c4152f6-2b28-4625-a85f-fd0498a4e286.png)

**Comment by AT14C** [comment]
Also here's a log from me running the older stable release with `+vk_validation 2` if it helps
[log.txt](https://github.com/yquake2/ref_vk/files/10189710/log.txt)

**Comment by turol** [comment]
There's nothing especially helpful here. Please attach a full log with the new (failing) ref_vk and the output of `vulkaninfo`. Also it would be useful if we added more logging. We should log all memory heap info, on failing allocation we should log information (especially size) about the allocation and we should have a cvar for logging all allocation info always.

**Comment by 0lvin** [comment]
Could you please try with validation_force branch? https://github.com/yquake2/ref_vk/commit/6cead718c1bd74d7574fd06b2e19443437fa4eca should provide more information what is going wrong.

**Comment by AT14C** [comment]
[validation_force.txt](https://github.com/yquake2/ref_vk/files/10198440/validation_force.txt)
[vulkaninfo.txt](https://github.com/yquake2/ref_vk/files/10198441/vulkaninfo.txt)

**Comment by 0lvin** [comment]
Could you please try with https://github.com/yquake2/ref_vk/tree/validation_old and https://github.com/yquake2/ref_vk/tree/validation_force? Are both working? Which of branch produces better fps with? 
```
r_validation  0
timedemo 1
demomap demo1.dm2
```

**Comment by AT14C** [comment]
Both work, but there is an obvious performance difference. For `validation_force` the demo runs slightly faster than normal speed, taking a total of 29.3 seconds to complete, while `validation_old` finishes in 0.8 seconds. Both builds were compiled with debug flags though, so they could possibly run faster, but I'd imagine the large difference between the two would still be the same.

Here's the stats:
`validation_force: 689 frames, 29.3 seconds: 23.5 fps`
`validation_old: 689 frames, 0.8 seconds: 836.2 fps`

**Comment by 0lvin** [comment]
Could you please check, and reopen bug if issue is still exists?

**Comment by AT14C** [comment]
Ok I tried the fork you made and it works perfectly fine and runs great too, I think you fixed it :+1:

**Comment by 0lvin** [comment]
Thank you, I have created v1.0.3 tag.
