### ISSUE TITLE
Windows binary releases

### ISSUE THREAD

**Issue by Yamagi** [yquake2/ref_vk#4]
I definitely want to do binary releases for Windows and source releases for Linux. The big question is how we want to implement them. I see at least two ways:

* Do it the same way as the addons: A source a release for Linux and ship a binary with the Windows binary bundle. This would be the easiest way for Windows users, because it's still one integrated bundle for them. Linux maintainers can build upon the addons, it would be more or less the same with another source archive.
* Use Github releases: Tag releases in this repository, attach the Windows `ref_vk.dll` to it. The big advantage is, that we can do Vulkan releases detached from the YQ2 release cycle and ship Windows binaries without complete test builds. The disadvantage is, that the user must download the Windows binary bundle and additionally the `ref_vk.dll` if they want to use Vulkan.

Any comments?

**Comment by kondrak** [comment]
I found GitHub releases quite convenient for this purpose, tags solved the problem of tagging specific commits for Linux/MacOS and it was just a matter of attaching properly built binary for download (now could be probably done in conjunction with GitHub actions).

**Comment by Yamagi** [comment]
I've opted for Github releases. See: https://github.com/yquake2/ref_vk/releases
