### ISSUE TITLE
ref_vk.so has incompatible api_version 0

### ISSUE THREAD

**Issue by mvrk69** [yquake2/ref_vk#49]
Hi,

I just compiled it on my Fedora 37 and when i try to use it i get this error:

]vid_renderer vk

]/vid_restart
----- refresher initialization -----
Loading library: ref_vk.so
Byte ordering: little endian

Cmd_RemoveCommand: vk_strings not added
Cmd_RemoveCommand: vk_mem not added
Cmd_RemoveCommand: imagelist not added
Cmd_RemoveCommand: screenshot not added
Cmd_RemoveCommand: modellist not added
ref_vk.so has incompatible api_version 0!
Retrying with gl3...

Any idea what might be the problem?

**Comment by 0lvin** [comment]
Have you used version from master?

Could you please try with master from yquake2   repository?

**Comment by mvrk69** [comment]
I was using release 1.0.5.

Now i tried with master and it works fine.

**Comment by Yamagi** [comment]
YQ2 8.30 broke the renderer API. That was inevitable, we needed a way to communicate the actual resolution (which can be different from the requested resolution) between client and renderer to implement high dpi awareness. :/
