### ISSUE TITLE
Vulkan: game freezes if new game is selected right after launch

### ISSUE THREAD

**Issue by thesourcehim** [yquake2/ref_vk#7]
If I launch 'The Reckoning' with Vulkan renderer (latest ref_vk) and try to start new game, application becomes unresponsive. Workaround: select OpenGL, start the game, then switch to Vulkan. Even if I select new game again after this, it starts fine. So the freeze only happens if application is started with Vulkan and then I try to start new game right after that. This only happens in this mod, original game and rogue work fine.

**Comment by Yamagi** [comment]
I've moved this issue to the rev_vk repo. Chances for it getting noticed by the right people are higher over there. :)

**Comment by 0lvin** [comment]
@thesourcehim What operation system have you used? Could you please share more information?

I can't reproduce such issues on linux with default set of textures.

**Comment by thesourcehim** [comment]
Linux Fedora 34.
nvidia GeForce 740M

ls -l xatrix
-rwxrwxrwx 1 thesource thesource     3284 jan 24  2020 config.cfg
-rwxrwxr-x 1 thesource thesource  1153808 jun 18 09:55 game.so
drwxr-xr-x 2 thesource thesource     4096 jun 18 09:55 maps
-rwxrwxrwx 1 thesource thesource 93310499 jan 24  2020 pak0.pak
-rwxrwxrwx 1 thesource thesource      766 jan 24  2020 q2.ico
-rw-rw-r-- 1 thesource thesource 24992193 jan 28  2020 textures.zip
drwxrwxr-x 2 thesource thesource     4096 jan 24  2020 video

maps contains map fixes from xatrix repo
textures.zip is from http://www-personal.umich.edu/~jimw/q2/Quake2/xatrix/

ls -l baseq2
-rwxrwxrwx 1 thesource thesource      3254 jan 24  2020 config.cfg
-rwxrwxr-x 1 thesource thesource    823144 jun 18 09:55 game.so
drwxr-xr-x 2 thesource thesource      4096 jun 18 09:55 maps
-rwxrwxrwx 1 thesource thesource      1063 jan 24  2020 maps.lst
-rw-rw-r-- 1 thesource thesource  17767691 jan 28  2020 models.zip
drwxrwxr-x 2 thesource thesource      4096 jan 28  2020 music
-rwxrwxrwx 1 thesource thesource 183997730 jan 24  2020 pak0.pak
-rwxrwxrwx 1 thesource thesource  12992754 jan 24  2020 pak1.pak
-rwxrwxrwx 1 thesource thesource     45055 jan 24  2020 pak2.pak
drwxrwxr-x 6 thesource thesource      4096 jan 24  2020 players
-rw-rw-r-- 1 thesource thesource 307015717 jan 28  2020 q2xp0.zip
-rw-rw-r-- 1 thesource thesource  53400454 jan 28  2020 q2xpMdl.zip
-rw-rw-r-- 1 thesource thesource 395639113 jan 28  2020 textures_for_q2.zip
drwxrwxr-x 2 thesource thesource      4096 jan 24  2020 video

all additional files are from http://www-personal.umich.edu/~jimw/q2/Quake2/baseq2/

**Comment by thesourcehim** [comment]
I get these messages, when freeze happens (tried on both nvidia card and intel integrated):
QVk_BeginFrame:2099: VkResult verification failed: VK_ERROR_DEVICE_LOST
QVk_GetStagingBuffer:2466: VkResult verification failed: VK_ERROR_DEVICE_LOST
SubmitStagingBuffer:1218: VkResult verification failed: VK_ERROR_DEVICE_LOST
QVk_EndFrame:2159: VkResult verification failed: VK_ERROR_DEVICE_LOST

**Comment by Yamagi** [comment]
Just to be sure: There's no resolution change involved when the Vulkan device gets lost?

**Comment by thesourcehim** [comment]
I don't change resolution by myself, I just try start new game, but I do it while xatrix logo video is playing.

**Comment by thesourcehim** [comment]
Tested 0facda0, fixed.
