### ISSUE TITLE
High CPU and GPU usage

### ISSUE THREAD

**Issue by topnepu** [yquake2/ref_vk#9]
The Vulkan renderer seems to peg one of the CPU cores and the fans and temperature on my GPU ramp up too compared to the OpenGL one. Quake II shouldn't be this demanding.

**Comment by DanielGibson** [comment]
is this with *vertical sync* on or off? (try setting it to `yes`)

**Comment by topnepu** [comment]
it was with it off and yeah turning it on improved things. i thought i wouldn't need it because there's a fps cap at 300.

**Comment by Yamagi** [comment]
You can switch off busy waits with setting `busywaits 0`. That saves a lot of CPU time but will break the timings, you might see microstuttering and physic / movement problems.
